### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by B4s1c4llyM4ch1n3** [YourPalAxl/yourpalaxl.github.io#1]
<img width="1440" alt="W586 site lost bit" src="https://github.com/YourPalAxl/yourpalaxl.github.io/assets/161125421/4be58f14-9192-4eea-8290-4e979cace035">
I wonder what could be for...

**Comment by YourPalAxl** [comment]
It's an accidentally scrapped Javascript live clock.
I plan to reimplement it at some point
